# Generated by Django 3.0.3 on 2020-08-18 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='media/products/')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintime', models.DateTimeField()),
                ('logouttime', models.DateTimeField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=30)),
                ('ans', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.UserModel')),
            ],
        ),
    ]
