# Generated by Django 3.0.3 on 2020-08-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('usernum', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phno', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
