# Generated by Django 3.0.3 on 2020-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_productmodel_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
