# Generated by Django 3.0.3 on 2020-08-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200822_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='productid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
