# Generated by Django 3.0.3 on 2020-08-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200826_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmessage',
            name='productid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductModel'),
        ),
    ]
