# Generated by Django 3.0.3 on 2020-08-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200826_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='pid',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmessage',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductModel'),
        ),
    ]
